### ISSUE TITLE
Use Official ElasticSearch Client

### ISSUE THREAD

**Issue by s0x** [georocket/georocket#153]
Is there a reason why all requests to ElasticSearch are build manually instead of using the official java client? This results in strong coupling to the specific version. In some cases even a minor version change might break the ability to use georocket (e.g. Upgrade ES 5.0 to 5.5).

**Comment by michel-kraemer** [comment]
Yes, there is a reason:

* At the time we wrote the custom client, Elasticsearch didn't have a separate jar containing only the client. We had to include the complete Elasticsearch jar, just to use the REST API. In the meantime they released a low-level client that has almost no dependencies, but it is so low-level that it doesn't really have any benefits compared to our implementation.
* There is a high-level version of the REST client, but it - again - depends on the complete Elasticsearch jar.
* Our implementation integrates better with Vert.x because it uses the Vert.x HttpClient and therefore supports asynchronous calls without executeBlocking or context switches.

I'm closing this issue for now, but we'll keep an eye on the official client and how it progresses.
