### ISSUE TITLE
GeoJSON support

### ISSUE THREAD

**Issue by lordi** [georocket/georocket#20]
Is GeoJSON supported yet? The chunking would be easy here, since one GeoJSON object is typically one Feature.

**Comment by michel-kraemer** [comment]
No, GeoJSON is not supported yet. GeoRocket can only import/export XML at the moment.

You may convert JSON to XML. AFAIK this should work well since GeoRocket does not check namespaces or the validity of XML documents. You may use Jackson, for example, to do an easy conversion. See the following StackOverflow thread. Jackson also supports converting back from XML to JSON.
http://stackoverflow.com/questions/6742705/simplest-method-to-convert-json-to-xml

GeoJSON is one of the things that we want to implement next, so I'll keep this issue open to track the progress.

**Comment by michel-kraemer** [comment]
GeoJSON support is now ready in the `master` branch. It will be part of the soon be released version 1.0.0.

Cheers,
Michel
