### ISSUE TITLE
REST API to store invidiual chunks

### ISSUE THREAD

**Issue by lordi** [georocket/georocket#21]
Is there a REST API call to store one or multiple chunks in a layer (instead of the source files)?
For instance, when the application already chunked the data, and simply wants to store/index it with GeoRocket.

**Comment by michel-kraemer** [comment]
This is not possible through the HTTP API. You may use the server API (Java project georocket-server-api) instead. The right interface to use would be `Store`.

If you use the server API you'll basically write a GeoRocket extension. If you want to keep everything on your client, then we need to extend the HTTP interface. Pull requests are very welcome :-)

**Comment by michel-kraemer** [comment]
Indeed this would be a very nice addition for the HTTP API. I'll leave this issue open, so we can implement it eventually.

**Comment by michel-kraemer** [comment]
I've discussed this issue with @andrej-sajenko. We came to the conclusion that the current API is already capable of doing what you suggest.

In GeoRocket chunks are stored together with their parent XML elements. Each chunk is a valid XML file itself. For example, given the following source file:

```xml
<root>
  <chunk>
    <content>Hello</content>
  </chunk>
  <chunk>
    <content>World</content>
  </chunk>
</root>
```

When you import this file in GeoRocket it will be split into the following two chunks:

```xml
<root>
  <chunk>
    <content>Hello</content>
  </chunk>
</root>
```

```xml
<root>
  <chunk>
    <content>World</content>
  </chunk>
</root>
```

The root element will be kept in all chunks so that each of them is a valid XML file.

This means no matter if you import the source file or the two chunks individually, the result will always be the same.

I'm closing this issue because I think there is nothing to be implemented. If you want to discuss the issue further feel free to reopen it.

Cheers,
Michel
