### ISSUE TITLE
Cannot search for GML IDs anymore

### ISSUE THREAD

**Issue by michel-kraemer** [georocket/georocket#53]
I can't search for GML IDs anymore. If I run

    georocket-cli/build/install/georocket-cli/bin/georocket search ID_147_D

then GeoRocket will return the whole data store. Internally it generates the following Elasticsearch query:

    {"query":{"bool":{"should":{"bool":{"should":[
        {"multi_match":{"query":"ID_147_D","fields":["genAttrs.*"]}},
        {"term":{"gmlIds":"ID_147_D"}}]}},
    "must":{"bool":{"should":[{"term":{"_id":"/store/"}},{"prefix":{"_id":"/store/"}}]}}}}}

If I remove the `must` part like this:

     {"query":{"bool":{"should":{"bool":{"should":[
        {"multi_match":{"query":"ID_147_D","fields":["genAttrs.*"]}},
        {"term":{"gmlIds":"ID_147_D"}}]}}}}}

Then Elasticsearch returns only one chunk.

**Comment by ykammeyer** [comment]
In a prior version of GeoRocket, the Elasticsearch query was _filtered_ through "setPostFilter(query)", of the QueryBuilder class. Maybe the store is returned because "query" API is used instead of ["post_filter"](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-post-filter.html). A documentation can be found at ["Queries and Filters"](https://www.elastic.co/guide/en/elasticsearch/guide/current/_queries_and_filters.html).

Does the substitution of _query_ with _post_filter_ produces the expected result?

**Comment by michel-kraemer** [comment]
Nice catch. Amazing. Thank you so much!
